### ISSUE TITLE
Not work with ES6 default parameters

### ISSUE THREAD

**Issue by ndaidong** [dominictarr/curry#32]
Hi there,

The following script works:

```
var add = curry((x, y) => {
  return x + y;
});

add(1, 2); // return 3
```

The following script does not work correctly:

```
curry((x = 0, y = 0) => {
  return x + y;
});

add(1, 2); // return 0
```

It may relate to the context, with apply or call somewhere.

Regards,
Dong

**Comment by ghost** [comment]
This might be because of the `length` of the function.
When you use ES6 default parameters, they will not be taken in account on the functions `length` property.

for example:
``` javascript
const add = (x, y) => x + y
add.length // returns 2

const addWithDefaultParameters = (x = 0, y = 0) => x + y
addWithDefaultParameters.length // returns 0
```

The curry function uses the length of the function to figure out some stuff [right here](https://github.com/dominictarr/curry/blob/master/curry.js#L70) on line 70.

For more information about the `length` property of a function check the [MDN entry](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length).

I hope this is somehow helpful for solving this issue.

edit: Adding link to source.

**Comment by guillaumearm** [comment]
Hi every currying users :-D

in ES6, __default parameters__ are a bit like __variadic functions__.
you need to fix arity of there functions with `curry.to` :
```js
curry.to(2, (x = 0, y = 0) => {
  return x + y;
});
```

or doing something like this (I prefer the first solution) : 
```js
curry((x, y) => {
  return (x || 0) + (y || 0);
});
```

**Comment by ndaidong** [comment]
@FrankVanVuuren thank you for pointing out the core cause. 
@guillaumearm thanks, your way works for me.
